import { createHash } from "node:crypto";
import { readFile, writeFile } from "node:fs/promises";
import { relative, resolve } from "node:path";

type Rewrite = { sourceText: string; displayText: string };

const root = resolve(import.meta.dirname, "..");
const skillRoot = resolve(root, "skills/9701-cuecaption");
const policyFiles = [
  "SKILL.md",
  "live-policy.md",
  "references/nomenclature.md",
  "references/formula-notation.md",
  "references/reaction-conventions.md",
  "references/mechanism-conventions.md",
  "references/ambiguity-policy.md",
  "references/syllabus-boundary.md",
  "data/nomenclature.yaml",
  "data/notation.yaml",
] as const;
const serverOutput = resolve(root, "server/planner/generated/cuecaption-policy.ts");
const clientOutput = resolve(root, "src/planner/generated/cuecaption-policy.ts");

function yamlPairs(source: string, section: string, sourceKey: string, outputKey: string): Rewrite[] {
  const records: Array<Record<string, string>> = [];
  let active = false;
  let current: Record<string, string> | undefined;
  for (const line of source.split("\n")) {
    const sectionMatch = line.match(/^([A-Za-z][A-Za-z0-9]*):\s*$/);
    if (sectionMatch) {
      if (current) records.push(current);
      current = undefined;
      active = sectionMatch[1] === section;
      continue;
    }
    if (!active) continue;
    const first = line.match(/^  - ([A-Za-z][A-Za-z0-9]*):\s*(.+)$/);
    if (first) {
      if (current) records.push(current);
      current = { [first[1]]: first[2].trim() };
      continue;
    }
    const field = line.match(/^    ([A-Za-z][A-Za-z0-9]*):\s*(.+)$/);
    if (field && current) current[field[1]] = field[2].trim();
  }
  if (current) records.push(current);
  return records.flatMap((record) => record[sourceKey] && record[outputKey]
    ? [{ sourceText: record[sourceKey], displayText: record[outputKey] }]
    : []);
}

function generatedHeader(sourceHash: string): string {
  return `// Generated by scripts/generate-cuecaption-policy.ts. Do not edit by hand.\n// CueCaption source SHA-256: ${sourceHash}\n`;
}

async function expectedOutputs() {
  const sources = await Promise.all(policyFiles.map(async (path) => ({ path, content: await readFile(resolve(skillRoot, path), "utf8") })));
  const sourceHash = createHash("sha256").update(sources.map(({ path, content }) => `${path}\0${content}`).join("\0")).digest("hex");
  const notation = sources.find(({ path }) => path === "data/notation.yaml")!.content;
  const nomenclature = sources.find(({ path }) => path === "data/nomenclature.yaml")!.content;
  const livePolicy = sources.find(({ path }) => path === "live-policy.md")!.content.trim();
  const symbolicRewrites = [
    ...yamlPairs(notation, "symbolicRewrites", "plain", "displayText"),
    ...yamlPairs(notation, "relationshipRewrites", "plain", "displayText"),
  ];
  const canonicalRewrites = [
    ...yamlPairs(notation, "formulaTypography", "spoken", "canonicalText"),
    ...yamlPairs(nomenclature, "surfaceVariants", "spoken", "canonical"),
  ];
  const sourcePaths = policyFiles.map((path) => `skills/9701-cuecaption/${path}`);
  return {
    [serverOutput]: `${generatedHeader(sourceHash)}export const CUECAPTION_POLICY_SOURCE_HASH = ${JSON.stringify(sourceHash)};\nexport const CUECAPTION_POLICY_SOURCE_FILES = ${JSON.stringify(sourcePaths, null, 2)} as const;\n/** Explicit compact runtime subset from skills/9701-cuecaption/live-policy.md. */\nexport const LIVE_CUECAPTION_POLICY = ${JSON.stringify(livePolicy)};\n`,
    [clientOutput]: `${generatedHeader(sourceHash)}export const CUECAPTION_POLICY_SOURCE_HASH = ${JSON.stringify(sourceHash)};\nexport const CUECAPTION_CANONICAL_REWRITES = ${JSON.stringify(canonicalRewrites, null, 2)} as const;\nexport const CUECAPTION_SYMBOLIC_REWRITES = ${JSON.stringify(symbolicRewrites, null, 2)} as const;\n`,
  };
}

async function main() {
  const check = process.argv.slice(2).includes("--check");
  const outputs = await expectedOutputs();
  for (const [path, expected] of Object.entries(outputs)) {
    if (check) {
      const actual = await readFile(path, "utf8").catch(() => "");
      if (actual !== expected) throw new Error(`${relative(root, path)} is stale; run npm run generate:cuecaption-policy`);
    } else {
      await writeFile(path, expected, "utf8");
    }
  }
  console.log(check ? "CueCaption generated policy is in sync." : "Generated CueCaption planner policy and rewrite tables.");
}

main().catch((error: unknown) => {
  console.error(error instanceof Error ? error.message : String(error));
  process.exitCode = 1;
});
